name: CI/CD for sat-nhap

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint code
        run: |
          pip install flake8
          flake8 api_sap_nhap.py sap_nhap_simple.py
      - name: Test import
        run: |
          python -c "import api_sap_nhap"

# Nếu muốn deploy lên dịch vụ, thêm bước deploy ở đây (Heroku, Railway, Render...)
# Ví dụ deploy Heroku:
# - name: Deploy to Heroku
#   uses: akhileshns/heroku-deploy@v3.12.12
#   with:
#     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#     heroku_app_name: "sat-nhap-api"
#     heroku_email: "your-email@example.com"
